# -*- coding: utf-8 -*-
"""football.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fn8mvJ0euM1zoy4L6dStMRqJVe4DeBBu

# ⚽ **Analyse du Football International (1872–2025)**
### Projet — Exploration & Statistiques
"""



import pandas as pd
import kagglehub
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as mtick
import os

# ── CREAR CARPETAS NECESARIAS ────────────
# Crear las carpetas si no existen
os.makedirs("data_clean", exist_ok=True)
os.makedirs("outputs/graphs", exist_ok=True)
print("✅ Carpetas creadas: data_clean/, outputs/graphs/")

"""# Charger les Données

Téléchargement
"""

path = kagglehub.dataset_download("martj42/international-football-results-from-1872-to-2017")
print("Path:", path)

"""Chargement"""

results      = pd.read_csv(f"{path}/results.csv")
shootouts    = pd.read_csv(f"{path}/shootouts.csv")
goalscorers  = pd.read_csv(f"{path}/goalscorers.csv")
former_names = pd.read_csv(f"{path}/former_names.csv")

dfs = {
    "results":      results,
    "shootouts":    shootouts,
    "goalscorers":  goalscorers,
    "former_names": former_names,
}

print(dfs)

"""Inspection initiale"""

for name, df in dfs.items():
    print(f"\n{'='*55}")
    print(f"  {name.upper()}")
    print(f"{'='*55}")
    print(f"  Lignes × Colonnes : {df.shape}")
    print(f"  Colonnes          : {list(df.columns)}")
    print(f"\n  Types de données :")
    print(df.dtypes.to_string())
    print(f"\n  Valeurs nulles par colonne :")
    print(df.isnull().sum().to_string())
    print(f"\n  Doublons exacts : {df.duplicated().sum()}")
    print(f"\n  3 premières lignes :")
    print(df.head(3).to_string())

"""# Nettoyage

Conversion des dates
"""

for name, df in dfs.items():
    if "date" in df.columns:
        df["date"] = pd.to_datetime(df["date"], errors="coerce")
        invalides = df["date"].isnull().sum()
        if invalides:
            print(f"[{name}] ⚠️  {invalides} dates invalides → seront supprimées")
            dfs[name] = df.dropna(subset=["date"])

"""Suppression des doublons"""

for name, df in dfs.items():
    avant = len(df)
    dfs[name] = df.drop_duplicates()
    supprimes = avant - len(dfs[name])
    if supprimes:
        print(f"[{name}] 🗑️  {supprimes} doublons supprimés")

"""Nettoyage des espaces dans les colonnes texte"""

cols_texte = {
    "results":      ["home_team", "away_team", "tournament", "city", "country"],
    "shootouts":    ["home_team", "away_team", "winner", "first_shooter"],
    "goalscorers":  ["home_team", "away_team", "team", "scorer"],
    "former_names": ["current", "former"],
}
for name, cols in cols_texte.items():
    for col in cols:
        if col in dfs[name].columns:
            dfs[name][col] = dfs[name][col].str.strip()

"""Normalisation des colonnes booléennes"""

for col in ["neutral", "own_goal", "penalty"]:
    for name, df in dfs.items():
        if col in df.columns:
            dfs[name][col] = df[col].astype(str).str.strip().str.upper().map(
                {"TRUE": True, "FALSE": False, "1": True, "0": False}
            )

"""Vérification des scores non négatifs"""

neg_domicile = (dfs["results"]["home_score"] < 0).sum()
neg_exterieur = (dfs["results"]["away_score"] < 0).sum()
if neg_domicile or neg_exterieur:
    print(f"[results] ⚠️  Scores négatifs : domicile={neg_domicile}, extérieur={neg_exterieur}")
else:
    print("[results] ✅ Aucun score négatif détecté")

"""Conversion des dates de début/fin dans former_names"""

for col in ["start_date", "end_date"]:
    if col in dfs["former_names"].columns:
        dfs["former_names"][col] = pd.to_datetime(
            dfs["former_names"][col], errors="coerce"
        )

"""**RÉAFFECTATION DES VARIABLES NETTOYÉES**"""

results      = dfs["results"]
shootouts    = dfs["shootouts"]
goalscorers  = dfs["goalscorers"]
former_names = dfs["former_names"]

"""Résumé final"""

print("\n" + "="*55)
print("  RÉSUMÉ FINAL — DONNÉES NETTOYÉES")
print("="*55)
for name, df in dfs.items():
    print(f"  {name:<15} → {df.shape[0]:>6,} lignes  |  {df.shape[1]} colonnes  |  "
          f"{df.isnull().sum().sum()} valeurs nulles restantes")
print("\n✅ Nettoyage terminé. Les DataFrames sont prêts.\n")

"""* Shootouts a 429 valeurs nulles mais sur seulement 675 lignes"""

print(shootouts)

"""VÉRIFICATION : NaN dans first_shooter"""

# Séparer les lignes avec et sans first_shooter
avec_first = shootouts[shootouts["first_shooter"].notna()]
sans_first = shootouts[shootouts["first_shooter"].isna()]

print(f"  Enregistrements AVEC first_shooter : {len(avec_first)}")
print(f"  Enregistrements SANS first_shooter : {len(sans_first)}")

# Vérifier si ces lignes ont quand même un gagnant
print(f"\n  Parmi les NaN dans first_shooter...")
print(f"  → Ont-ils un 'winner' enregistré ?")
print(sans_first["winner"].value_counts(dropna=False).to_string())

# Afficher quelques exemples
print(f"\n  Exemples de lignes avec first_shooter = NaN :")
print(sans_first.head(10).to_string())

"""REMPLACEMENT DES NaN DANS first_shooter

"""

# Copie de travail — ne jamais modifier shootouts directement
shootouts_clean = shootouts.copy()
shootouts_clean["first_shooter"] = shootouts_clean["first_shooter"].fillna("Inconnu")

# Ajout d'une colonne indicatrice pour distinguer les valeurs connues des inconnues
shootouts_clean["first_shooter_connu"] = shootouts["first_shooter"].notna()

# Vérification finale
print("  Vérification après remplacement :")
print(f"  NaN restants dans first_shooter      : {shootouts_clean['first_shooter'].isna().sum()}")
print(f"  Enregistrements avec valeur connue   : {shootouts_clean['first_shooter_connu'].sum()}")
print(f"  Enregistrements avec valeur inconnue : {(~shootouts_clean['first_shooter_connu']).sum()}")

# Mise à jour dans le dictionnaire principal
dfs["shootouts"] = shootouts_clean

"""* Analyse des valeurs manquantes dans la colonne 'first_shooter' :
Sur 675 enregistrements, 429 ont un NaN dans cette colonne (63.5%). Après vérification, tous ces enregistrements possèdent bien un 'winner', ce qui confirme que les tirs au but ont bien eu lieu.
* L'absence de données s'explique par un manque de documentation historique : les matchs concernés datent majoritairement des années 1960-1970, une époque où le suivi statistique détaillé n'était pas encore systématique.

* **DÉCISION :** on conserve le DataFrame original intact et on travaille sur une copie. Remplacer les NaN directement serait risqué car on introduirait une valeur inventée là où l'information est simplement absente.

DIAGNOSTIC DES VALEURS NULLES : results & goalscorers
"""

# Analyse détaillée de results
print("=" * 55)
print("  RESULTS — Détail des valeurs nulles")
print("=" * 55)
nuls_results = results.isnull().sum()
nuls_results = nuls_results[nuls_results > 0]
for col, n in nuls_results.items():
    pct = (n / len(results)) * 100
    print(f"  {col:<20} → {n:>5} nuls  ({pct:.2f}%)")

print(f"\n  Exemples de lignes avec des nuls :")
print(results[results.isnull().any(axis=1)].head(5).to_string())

# Analyse détaillée de goalscorers
print("\n" + "=" * 55)
print("  GOALSCORERS — Détail des valeurs nulles")
print("=" * 55)
nuls_goals = goalscorers.isnull().sum()
nuls_goals = nuls_goals[nuls_goals > 0]
for col, n in nuls_goals.items():
    pct = (n / len(goalscorers)) * 100
    print(f"  {col:<20} → {n:>5} nuls  ({pct:.2f}%)")

print(f"\n  Exemples de lignes avec des nuls :")
print(goalscorers[goalscorers.isnull().any(axis=1)].head(5).to_string())

"""**ANALYSE CONTEXTUELLE DES VALEURS NULLES**

Vérifier les matchs sans score dans results
"""

print("=" * 55)
print("  RESULTS — Matchs sans score")
print("=" * 55)
sans_score = results[results["home_score"].isna()]
print(f"  Total matchs sans score : {len(sans_score)}")
print(f"\n  Répartition par tournoi :")
print(sans_score["tournament"].value_counts().head(10).to_string())
print(f"\n  Répartition temporelle :")
print(f"  Année min : {sans_score['date'].dt.year.min()}")
print(f"  Année max : {sans_score['date'].dt.year.max()}")
print(f"\n  Exemples :")
print(sans_score.head(5).to_string())

"""Vérifier les buts sans buteur dans goalscorers"""

print("\n" + "=" * 55)
print("  GOALSCORERS — Buts sans buteur")
print("=" * 55)
sans_buteur = goalscorers[goalscorers["scorer"].isna()]
print(f"  Total buts sans buteur : {len(sans_buteur)}")
print(f"\n  Sont-ils des own goals ?")
print(sans_buteur["own_goal"].value_counts(dropna=False).to_string())
print(f"\n  Sont-ils des penaltys ?")
print(sans_buteur["penalty"].value_counts(dropna=False).to_string())

"""Vérifier les buts sans minute"""

print("\n" + "=" * 55)
print("  GOALSCORERS — Buts sans minute")
print("=" * 55)
sans_minute = goalscorers[goalscorers["minute"].isna()]
print(f"  Total buts sans minute : {len(sans_minute)}")
print(f"\n  Répartition temporelle :")
print(f"  Année min : {sans_minute['date'].dt.year.min()}")
print(f"  Année max : {sans_minute['date'].dt.year.max()}")
print(f"\n  Exemples :")
print(sans_minute.head(5).to_string())

"""**TRAITEMENT DES VALEURS NULLES : results & goalscorers**"""

# RESULTS — 72 matchs sans score
# Ces matchs peuvent être des matchs abandonnés, annulés ou mal documentés.
# On conserve l'original et on crée une copie sans ces lignes pour les analyses
# qui nécessitent des scores (calcul de moyennes, tendances, etc.)
results_original = results.copy()
results_clean = results.dropna(subset=["home_score", "away_score"]).copy()

print("=" * 55)
print("  RESULTS")
print("=" * 55)
print(f"  Lignes original : {len(results_original)}")
print(f"  Lignes clean    : {len(results_clean)}")
print(f"  Matchs écartés  : {len(results_original) - len(results_clean)}")

# GOALSCORERS — 11 buts sans buteur
# Ni own goals ni penaltys — l'identité du buteur est simplement inconnue.
# On conserve l'original et dans la copie on remplace par "Inconnu"
# pour maintenir la cohérence avec le traitement de first_shooter.
goalscorers_original = goalscorers.copy()
goalscorers_clean = goalscorers.copy()
goalscorers_clean["scorer"] = goalscorers_clean["scorer"].fillna("Inconnu")
goalscorers_clean["scorer_connu"] = goalscorers["scorer"].notna()

# GOALSCORERS — 184 buts sans minute
# Tous entre 1960 et 1997 — absence de documentation historique.
# On conserve les NaN car -1 ou 0 induiraient en erreur les analyses temporelles.
# On ajoute uniquement une colonne indicatrice.
goalscorers_clean["minute_connue"] = goalscorers["minute"].notna()

print("\n" + "=" * 55)
print("  GOALSCORERS")
print("=" * 55)
print(f"  Lignes original            : {len(goalscorers_original)}")
print(f"  Buts avec buteur inconnu   : {(~goalscorers_clean['scorer_connu']).sum()}")
print(f"  Buts avec minute inconnue  : {(~goalscorers_clean['minute_connue']).sum()}")
print(f"  NaN restants dans scorer   : {goalscorers_clean['scorer'].isna().sum()}")
print(f"  NaN restants dans minute   : {goalscorers_clean['minute'].isna().sum()}")

# Mise à jour dans le dictionnaire principal
dfs["results"]     = results_clean
dfs["goalscorers"] = goalscorers_clean

print("\n✅ Traitement terminé. Récapitulatif final :")
for name, df in dfs.items():
    print(f"  {name:<15} → {df.shape[0]:>6,} lignes  |  "
          f"{df.isnull().sum().sum()} valeurs nulles restantes")




# ══════════════════════════════════════════════════════════
# SECTION 2 — COUPE DU MONDE FIFA 2026
# Analyse historique & groupes officiels
# ══════════════════════════════════════════════════════════

# ── 2.1 DÉFINITION DES GROUPES OFFICIELS FIFA 2026 ────────
# Source : Tirage au sort FIFA — 5 décembre 2025, Washington D.C.
# Format inédit : 48 équipes / 12 groupes / 104 matchs
# Tournoi : 11 juin → 19 juillet 2026 (USA, Canada, Mexique)

groupes_2026 = {
    "A": ["Mexico", "South Africa", "South Korea", "Czechia"],
    "B": ["Canada", "Bosnia and Herzegovina", "Qatar", "Switzerland"],
    "C": ["Brazil", "Morocco", "Haiti", "Scotland"],
    "D": ["United States", "Paraguay", "Australia", "Turkey"],
    "E": ["Germany", "Curacao", "Ivory Coast", "Ecuador"],
    "F": ["Netherlands", "Japan", "Sweden", "Tunisia"],
    "G": ["Belgium", "Egypt", "Iran", "New Zealand"],
    "H": ["Spain", "Cape Verde", "Saudi Arabia", "Uruguay"],
    "I": ["France", "Senegal", "Iraq", "Norway"],
    "J": ["Argentina", "Algeria", "Austria", "Jordan"],
    "K": ["Portugal", "DR Congo", "Uzbekistan", "Colombia"],
    "L": ["England", "Croatia", "Ghana", "Panama"],
}

# Liste à plat de toutes les équipes qualifiées
equipes_2026 = [equipe for groupe in groupes_2026.values() for equipe in groupe]

print("=" * 55)
print("  GROUPES FIFA WORLD CUP 2026")
print("=" * 55)
for groupe, equipes in groupes_2026.items():
    print(f"  Groupe {groupe} : {' | '.join(equipes)}")
print(f"\n  Total équipes : {len(equipes_2026)}")

# ── 2.2 FILTRER L'HISTORIQUE FIFA WORLD CUP ───────────────
# Isoler uniquement les matchs de Coupe du Monde depuis 1930
wc_results = results_clean[
    results_clean["tournament"] == "FIFA World Cup"
].copy()

print(f"\n  Matchs FIFA World Cup dans le dataset : {len(wc_results):,}")
print(f"  Période couverte : {wc_results['date'].dt.year.min()} → {wc_results['date'].dt.year.max()}")
print(f"\n  Éditions disponibles :")
print(wc_results["date"].dt.year.value_counts().sort_index().to_string())



# ══════════════════════════════════════════════════════════
# 2.3 PERFORMANCE HISTORIQUE PAR ÉQUIPE — FIFA WORLD CUP
# Base pour le classement et l'analyse par groupe
# ══════════════════════════════════════════════════════════

import os
os.makedirs("outputs/graphs", exist_ok=True)

# ── Calcul des statistiques pour chaque équipe ────────────
# On analyse chaque équipe sous ses deux rôles : domicile et extérieur
# puis on agrège pour obtenir les stats globales en Coupe du Monde

stats_liste = []

for equipe in equipes_2026:

    # Matchs où l'équipe jouait à domicile
    dom = wc_results[wc_results["home_team"] == equipe]
    # Matchs où l'équipe jouait à l'extérieur
    ext = wc_results[wc_results["away_team"] == equipe]

    # Calcul des victoires, nuls, défaites
    v_dom  = (dom["home_score"] > dom["away_score"]).sum()
    n_dom  = (dom["home_score"] == dom["away_score"]).sum()
    d_dom  = (dom["home_score"] < dom["away_score"]).sum()

    v_ext  = (ext["away_score"] > ext["home_score"]).sum()
    n_ext  = (ext["away_score"] == ext["home_score"]).sum()
    d_ext  = (ext["away_score"] < ext["home_score"]).sum()

    # Agrégation
    pj = len(dom) + len(ext)   # Parties jouées
    v  = v_dom + v_ext         # Victoires
    n  = n_dom + n_ext         # Nuls
    d  = d_dom + d_ext         # Défaites

    # Buts
    bf = dom["home_score"].sum() + ext["away_score"].sum()   # Buts pour
    bc = dom["away_score"].sum() + ext["home_score"].sum()   # Buts contre
    db = bf - bc                                              # Différence de buts

    # Points FIFA (3 par victoire, 1 par nul)
    pts = v * 3 + n

    # Taux de victoire
    taux_v = round(v / pj * 100, 1) if pj > 0 else 0

    stats_liste.append({
        "equipe":   equipe,
        "PJ":       pj,
        "V":        v,
        "N":        n,
        "D":        d,
        "BF":       int(bf),
        "BC":       int(bc),
        "DB":       int(db),
        "PTS":      pts,
        "taux_V":   taux_v,
    })

# Créer le DataFrame de statistiques
stats_wc = pd.DataFrame(stats_liste).sort_values("PTS", ascending=False).reset_index(drop=True)
stats_wc.index += 1   # Classement à partir de 1

# ── Affichage du classement historique ────────────────────
print("=" * 75)
print("  CLASSEMENT HISTORIQUE EN COUPE DU MONDE — Équipes qualifiées 2026")
print("=" * 75)
print(f"  {'#':<4} {'Équipe':<25} {'PJ':>4} {'V':>4} {'N':>4} {'D':>4} "
      f"{'BF':>5} {'BC':>5} {'DB':>5} {'PTS':>5} {'%V':>6}")
print("  " + "-" * 71)
for idx, row in stats_wc.iterrows():
    print(f"  {idx:<4} {row['equipe']:<25} {row['PJ']:>4} {row['V']:>4} "
          f"{row['N']:>4} {row['D']:>4} {row['BF']:>5} {row['BC']:>5} "
          f"{row['DB']:>5} {row['PTS']:>5} {row['taux_V']:>5.1f}%")

# ── Visualisation — Top 10 équipes par points historiques ─
top10 = stats_wc.head(10)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle("Performance historique en Coupe du Monde\nÉquipes qualifiées 2026",
             fontsize=14, fontweight="bold")

# Graphique 1 — Points historiques top 10
couleurs_bar = ["#042C53" if i == 0 else "#185FA5" if i < 3 else "#85B7EB"
                for i in range(len(top10))]
barres = axes[0].barh(top10["equipe"][::-1], top10["PTS"][::-1], color=couleurs_bar[::-1])
axes[0].set_title("Top 10 — Points historiques (V×3 + N×1)", fontweight="bold")
axes[0].set_xlabel("Points")
for barre, val in zip(barres, top10["PTS"][::-1]):
    axes[0].text(barre.get_width() + 1, barre.get_y() + barre.get_height()/2,
                 str(val), va="center", fontsize=9, fontweight="bold")

# Graphique 2 — Taux de victoire top 10
axes[1].barh(top10["equipe"][::-1], top10["taux_V"][::-1], color="#378ADD")
axes[1].set_title("Top 10 — Taux de victoire (%)", fontweight="bold")
axes[1].set_xlabel("Taux de victoire (%)")
axes[1].axvline(x=50, color="#EF9F27", linestyle="--", alpha=0.8, label="50% référence")
axes[1].legend()
for i, (barre, val) in enumerate(zip(axes[1].patches, top10["taux_V"][::-1])):
    axes[1].text(barre.get_width() + 0.3, barre.get_y() + barre.get_height()/2,
                 f"{val}%", va="center", fontsize=9, fontweight="bold")

plt.tight_layout()
plt.savefig("outputs/graphs/classement_historique_wc.png", dpi=150, bbox_inches="tight")
# plt.show()
print("\n✅ Graphique sauvegardé : outputs/graphs/classement_historique_wc.png")



# ── SAUVEGARDE DU CLASSEMENT HISTORIQUE EN CSV ────────────
# Permet de visualiser et partager facilement le classement
stats_wc.to_csv("data_clean/classement_historique_wc.csv", index=True)
print("✅ Classement sauvegardé : data_clean/classement_historique_wc.csv")


# ══════════════════════════════════════════════════════════
# 2.4 ANALYSE PAR GROUPE — FIFA WORLD CUP 2026
# Croisement du classement historique avec les groupes officiels
# ══════════════════════════════════════════════════════════

# ── Ajouter le groupe de chaque équipe au classement ──────
equipe_groupe = {equipe: groupe
                 for groupe, equipes in groupes_2026.items()
                 for equipe in equipes}

stats_wc["groupe"] = stats_wc["equipe"].map(equipe_groupe)

# ── Analyse détaillée par groupe ──────────────────────────
print("=" * 65)
print("  ANALYSE PAR GROUPE — COUPE DU MONDE 2026")
print("=" * 65)

resultats_groupes = []

for groupe in sorted(groupes_2026.keys()):
    equipes_du_groupe = groupes_2026[groupe]
    stats_groupe = stats_wc[stats_wc["groupe"] == groupe].copy()

    # Trier par points dans le groupe
    stats_groupe = stats_groupe.sort_values("PTS", ascending=False)

    print(f"\n  GROUPE {groupe}")
    print(f"  {'-' * 60}")
    print(f"  {'Équipe':<25} {'PJ':>4} {'V':>4} {'PTS':>5} {'%V':>6} {'DB':>5}")
    print(f"  {'-' * 60}")

    favori = None
    for _, row in stats_groupe.iterrows():
        # Identifier le favori du groupe (le plus de points)
        if favori is None:
            favori = row["equipe"]
            marqueur = " ⭐"
        else:
            marqueur = ""
        print(f"  {row['equipe']:<25} {row['PJ']:>4} {row['V']:>4} "
              f"{row['PTS']:>5} {row['taux_V']:>5.1f}% {row['DB']:>5}{marqueur}")

    # Débutants dans le groupe (0 matchs en Coupe du Monde)
    debutants = stats_groupe[stats_groupe["PJ"] == 0]["equipe"].tolist()
    if debutants:
        print(f"\n  ⚠️  Débutants en Coupe du Monde : {', '.join(debutants)}")

    # Sauvegarder le résumé du groupe
    resultats_groupes.append({
        "groupe":   groupe,
        "favori":   favori,
        "equipes":  " | ".join(equipes_du_groupe),
        "pts_favori": stats_groupe.iloc[0]["PTS"] if len(stats_groupe) > 0 else 0,
        "debutants": ", ".join(debutants) if debutants else "Aucun",
    })

# ── Résumé global des favoris ─────────────────────────────
print("\n\n" + "=" * 65)
print("  RÉSUMÉ — FAVORIS HISTORIQUES PAR GROUPE")
print("=" * 65)
print(f"\n  {'Groupe':<8} {'Favori historique':<25} {'PTS':>5}")
print(f"  {'-' * 40}")
for r in resultats_groupes:
    print(f"  {r['groupe']:<8} {r['favori']:<25} {r['pts_favori']:>5}")

# ── Sauvegarde ────────────────────────────────────────────
df_groupes = pd.DataFrame(resultats_groupes)
df_groupes.to_csv("data_clean/analyse_groupes_2026.csv", index=False)
stats_wc.to_csv("data_clean/classement_historique_wc.csv", index=True)

# ── Visualisation — Favoris par groupe ────────────────────
fig, ax = plt.subplots(figsize=(14, 7))

# Préparer les données : un point par équipe, coloré par groupe
couleurs_groupes = plt.cm.tab20.colors
groupe_labels = sorted(groupes_2026.keys())

for i, groupe in enumerate(groupe_labels):
    stats_g = stats_wc[stats_wc["groupe"] == groupe].sort_values("PTS", ascending=False)
    for j, (_, row) in enumerate(stats_g.iterrows()):
        couleur = couleurs_groupes[i % len(couleurs_groupes)]
        ax.scatter(row["taux_V"], row["PTS"], color=couleur, s=120, zorder=3)
        ax.annotate(f"{row['equipe']}\n(G{groupe})",
                    (row["taux_V"], row["PTS"]),
                    fontsize=7, ha="left", va="bottom",
                    xytext=(3, 3), textcoords="offset points")

ax.axvline(x=50, color="#EF9F27", linestyle="--", alpha=0.6, label="50% taux victoire")
ax.axhline(y=50, color="#85B7EB", linestyle="--", alpha=0.6, label="50 points")
ax.set_title("Performance historique par équipe — Coupe du Monde 2026\n"
             "Taux de victoire vs Points totaux", fontweight="bold", fontsize=13)
ax.set_xlabel("Taux de victoire (%)")
ax.set_ylabel("Points historiques totaux")
ax.legend(fontsize=9)

plt.tight_layout()
plt.savefig("outputs/graphs/analyse_groupes_2026.png", dpi=150, bbox_inches="tight")
# plt.show()
print("\n✅ Fichiers sauvegardés :")
print("   📄 data_clean/analyse_groupes_2026.csv")
print("   📄 data_clean/classement_historique_wc.csv")
print("   🖼️  outputs/graphs/analyse_groupes_2026.png")



# ══════════════════════════════════════════════════════════
# 2.5 PALMARÈS — TITRES ET FINALES EN COUPE DU MONDE
# Enrichissement du classement avec les titres historiques
# ══════════════════════════════════════════════════════════

# Palmarès manuel — titres officiels FIFA World Cup
# Source : FIFA (données non présentes dans le dataset)
palmares = {
    "Brazil":        {"titres": 5, "finales": 7,  "annees": "1958,1962,1970,1994,2002"},
    "Germany":       {"titres": 4, "finales": 8,  "annees": "1954,1974,1990,2014"},
    "Argentina":     {"titres": 3, "finales": 5,  "annees": "1978,1986,2022"},
    "France":        {"titres": 2, "finales": 3,  "annees": "1998,2018"},
    "Uruguay":       {"titres": 2, "finales": 2,  "annees": "1930,1950"},
    "England":       {"titres": 1, "finales": 1,  "annees": "1966"},
    "Spain":         {"titres": 1, "finales": 1,  "annees": "2010"},
    "Netherlands":   {"titres": 0, "finales": 3,  "annees": "—"},
    "Portugal":      {"titres": 0, "finales": 0,  "annees": "—"},
    "Belgium":       {"titres": 0, "finales": 0,  "annees": "—"},
    "Mexico":        {"titres": 0, "finales": 0,  "annees": "—"},
    "Croatia":       {"titres": 0, "finales": 1,  "annees": "—"},
    "Colombia":      {"titres": 0, "finales": 0,  "annees": "—"},
    "Switzerland":   {"titres": 0, "finales": 0,  "annees": "—"},
    "Japan":         {"titres": 0, "finales": 0,  "annees": "—"},
    "South Korea":   {"titres": 0, "finales": 0,  "annees": "—"},
    "Morocco":       {"titres": 0, "finales": 0,  "annees": "—"},
    "Senegal":       {"titres": 0, "finales": 0,  "annees": "—"},
    "Ecuador":       {"titres": 0, "finales": 0,  "annees": "—"},
    "Turkey":        {"titres": 0, "finales": 0,  "annees": "—"},
    "Australia":     {"titres": 0, "finales": 0,  "annees": "—"},
    "Iran":          {"titres": 0, "finales": 0,  "annees": "—"},
    "Ghana":         {"titres": 0, "finales": 0,  "annees": "—"},
    "Paraguay":      {"titres": 0, "finales": 0,  "annees": "—"},
    "Algeria":       {"titres": 0, "finales": 0,  "annees": "—"},
    "Austria":       {"titres": 0, "finales": 0,  "annees": "—"},
    "Norway":        {"titres": 0, "finales": 0,  "annees": "—"},
    "Scotland":      {"titres": 0, "finales": 0,  "annees": "—"},
    "Saudi Arabia":  {"titres": 0, "finales": 0,  "annees": "—"},
    "Tunisia":       {"titres": 0, "finales": 0,  "annees": "—"},
    "Sweden":        {"titres": 0, "finales": 1,  "annees": "—"},
    "South Africa":  {"titres": 0, "finales": 0,  "annees": "—"},
    "United States": {"titres": 0, "finales": 0,  "annees": "—"},
    "Egypt":         {"titres": 0, "finales": 0,  "annees": "—"},
    "New Zealand":   {"titres": 0, "finales": 0,  "annees": "—"},
    "Bosnia and Herzegovina": {"titres": 0, "finales": 0, "annees": "—"},
    "Canada":        {"titres": 0, "finales": 0,  "annees": "—"},
    "Qatar":         {"titres": 0, "finales": 0,  "annees": "—"},
    "Haiti":         {"titres": 0, "finales": 0,  "annees": "—"},
    "Curacao":       {"titres": 0, "finales": 0,  "annees": "—"},
    "Cape Verde":    {"titres": 0, "finales": 0,  "annees": "—"},
    "Iraq":          {"titres": 0, "finales": 0,  "annees": "—"},
    "Jordan":        {"titres": 0, "finales": 0,  "annees": "—"},
    "DR Congo":      {"titres": 0, "finales": 0,  "annees": "—"},
    "Uzbekistan":    {"titres": 0, "finales": 0,  "annees": "—"},
    "Panama":        {"titres": 0, "finales": 0,  "annees": "—"},
    "Czechia":       {"titres": 0, "finales": 0,  "annees": "—"},
    "Ivory Coast":   {"titres": 0, "finales": 0,  "annees": "—"},
    "Netherlands":   {"titres": 0, "finales": 3,  "annees": "—"},
}

# Intégrer le palmarès dans stats_wc
stats_wc["titres"]  = stats_wc["equipe"].map(lambda x: palmares.get(x, {}).get("titres", 0))
stats_wc["finales"] = stats_wc["equipe"].map(lambda x: palmares.get(x, {}).get("finales", 0))
stats_wc["annees_titres"] = stats_wc["equipe"].map(lambda x: palmares.get(x, {}).get("annees", "—"))

# ── Affichage enrichi ─────────────────────────────────────
print("=" * 72)
print("  PALMARÈS — ÉQUIPES QUALIFIÉES 2026 (titres & finales)")
print("=" * 72)
print(f"\n  {'Équipe':<25} {'Groupe':<8} {'PTS':>5} {'%V':>6} {'🏆':>4} {'Finales':>8}  Années")
print(f"  {'-' * 68}")

for _, row in stats_wc.sort_values("titres", ascending=False).iterrows():
    if row["titres"] > 0 or row["finales"] > 0:
        trophee = "🏆" * int(row["titres"]) if row["titres"] > 0 else "—"
        print(f"  {row['equipe']:<25} {row['groupe']:<8} {row['PTS']:>5} "
              f"{row['taux_V']:>5.1f}% {row['titres']:>4} {row['finales']:>8}  {row['annees_titres']}")

# ── Sauvegarde enrichie ───────────────────────────────────
stats_wc.to_csv("data_clean/classement_historique_wc.csv", index=True)

# ── Visualisation — Champions du monde dans les groupes ───
champions = stats_wc[stats_wc["titres"] > 0].sort_values("titres", ascending=False)

fig, ax = plt.subplots(figsize=(12, 5))
barres = ax.bar(champions["equipe"], champions["titres"],
                color=["#042C53", "#185FA5", "#185FA5", "#378ADD",
                       "#378ADD", "#85B7EB", "#85B7EB", "#85B7EB"],
                edgecolor="white", linewidth=0.5)

# Annoter avec les années
for barre, (_, row) in zip(barres, champions.iterrows()):
    ax.text(barre.get_x() + barre.get_width()/2, barre.get_height() + 0.05,
            f"Groupe {row['groupe']}", ha="center", fontsize=9, color="#042C53", fontweight="bold")
    ax.text(barre.get_x() + barre.get_width()/2, barre.get_height()/2,
            str(int(row["titres"])), ha="center", fontsize=14,
            color="white", fontweight="bold")

ax.set_title("Champions du Monde qualifiés pour 2026\nNombre de titres FIFA World Cup",
             fontweight="bold", fontsize=13)
ax.set_ylabel("Nombre de titres")
ax.set_ylim(0, 6.5)
ax.tick_params(axis="x", rotation=15)

plt.tight_layout()
plt.savefig("outputs/graphs/palmares_champions_2026.png", dpi=150, bbox_inches="tight")
# plt.show()
print("\n✅ Fichiers sauvegardés :")
print("   📄 data_clean/classement_historique_wc.csv  (enrichi avec palmarès)")
print("   🖼️  outputs/graphs/palmares_champions_2026.png")




# ══════════════════════════════════════════════════════════
# 2.6 GÉNÉRATION DES 12 VISUELS LINKEDIN — PAR GROUPE
# Une graphique + un texte de post par groupe
# ══════════════════════════════════════════════════════════

import os
os.makedirs("outputs/linkedin", exist_ok=True)

# ── Palette de couleurs par rang dans le groupe ───────────
def couleur_rang(rang, total):
    # Le favori en bleu foncé, les autres en dégradé
    palette = ["#042C53", "#185FA5", "#378ADD", "#85B7EB"]
    return palette[min(rang, total - 1)]

# ── Emoji drapeaux approximatifs par équipe ───────────────
drapeaux = {
    "Mexico": "🇲🇽", "South Africa": "🇿🇦", "South Korea": "🇰🇷", "Czechia": "🇨🇿",
    "Canada": "🇨🇦", "Bosnia and Herzegovina": "🇧🇦", "Qatar": "🇶🇦", "Switzerland": "🇨🇭",
    "Brazil": "🇧🇷", "Morocco": "🇲🇦", "Haiti": "🇭🇹", "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "United States": "🇺🇸", "Paraguay": "🇵🇾", "Australia": "🇦🇺", "Turkey": "🇹🇷",
    "Germany": "🇩🇪", "Curacao": "🇨🇼", "Ivory Coast": "🇨🇮", "Ecuador": "🇪🇨",
    "Netherlands": "🇳🇱", "Japan": "🇯🇵", "Sweden": "🇸🇪", "Tunisia": "🇹🇳",
    "Belgium": "🇧🇪", "Egypt": "🇪🇬", "Iran": "🇮🇷", "New Zealand": "🇳🇿",
    "Spain": "🇪🇸", "Cape Verde": "🇨🇻", "Saudi Arabia": "🇸🇦", "Uruguay": "🇺🇾",
    "France": "🇫🇷", "Senegal": "🇸🇳", "Iraq": "🇮🇶", "Norway": "🇳🇴",
    "Argentina": "🇦🇷", "Algeria": "🇩🇿", "Austria": "🇦🇹", "Jordan": "🇯🇴",
    "Portugal": "🇵🇹", "DR Congo": "🇨🇩", "Uzbekistan": "🇺🇿", "Colombia": "🇨🇴",
    "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "Croatia": "🇭🇷", "Ghana": "🇬🇭", "Panama": "🇵🇦",
}

# ── Génération des visuels et posts ──────────────────────
posts_linkedin = []

for groupe in sorted(groupes_2026.keys()):

    # Données du groupe triées par points
    stats_g = stats_wc[stats_wc["groupe"] == groupe].sort_values("PTS", ascending=False).reset_index(drop=True)
    favori  = stats_g.iloc[0]["equipe"]
    titres_favori = int(stats_g.iloc[0]["titres"])

    # ── Graphique ─────────────────────────────────────────
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.patch.set_facecolor("#F8FAFD")

    fig.suptitle(f"⚽ FIFA World Cup 2026 — Groupe {groupe}\nAnalyse historique",
                 fontsize=14, fontweight="bold", color="#042C53", y=1.02)

    couleurs = [couleur_rang(i, len(stats_g)) for i in range(len(stats_g))]

    # Barres horizontales — Points historiques
    equipes_labels = [f"{drapeaux.get(e, '')} {e}" for e in stats_g["equipe"]]
    barres = axes[0].barh(equipes_labels[::-1], stats_g["PTS"][::-1],
                          color=couleurs[::-1], edgecolor="white", linewidth=0.8)
    axes[0].set_title("Points historiques en Coupe du Monde", fontweight="bold",
                      fontsize=11, color="#042C53")
    axes[0].set_xlabel("Points (V×3 + N×1)", color="#042C53")
    axes[0].set_facecolor("#F8FAFD")
    for barre, val in zip(barres, stats_g["PTS"][::-1]):
        axes[0].text(max(barre.get_width() - 5, 1),
                     barre.get_y() + barre.get_height()/2,
                     str(int(val)), va="center", ha="right",
                     color="white", fontsize=10, fontweight="bold")

    # Barres horizontales — Taux de victoire
    barres2 = axes[1].barh(equipes_labels[::-1], stats_g["taux_V"][::-1],
                           color=couleurs[::-1], edgecolor="white", linewidth=0.8)
    axes[1].set_title("Taux de victoire (%)", fontweight="bold",
                      fontsize=11, color="#042C53")
    axes[1].set_xlabel("Taux de victoire (%)", color="#042C53")
    axes[1].set_facecolor("#F8FAFD")
    axes[1].axvline(x=50, color="#EF9F27", linestyle="--", alpha=0.7, label="50% référence")
    axes[1].legend(fontsize=8)
    for barre, val in zip(barres2, stats_g["taux_V"][::-1]):
        offset = -3 if val > 10 else 1
        axes[1].text(max(barre.get_width() + offset, 1),
                     barre.get_y() + barre.get_height()/2,
                     f"{val:.1f}%", va="center", ha="right" if val > 10 else "left",
                     color="white" if val > 10 else "#042C53",
                     fontsize=10, fontweight="bold")

    # Légende des titres dans le coin
    titres_texte = "\n".join([
        f"🏆 {row['equipe']} — {int(row['titres'])} titre(s)"
        for _, row in stats_g.iterrows() if row["titres"] > 0
    ]) or "Aucun champion du monde dans ce groupe"

    fig.text(0.5, -0.05, titres_texte, ha="center", fontsize=9,
             color="#042C53", style="italic")

    plt.tight_layout()
    chemin_graphique = f"outputs/linkedin/groupe_{groupe}.png"
    plt.savefig(chemin_graphique, dpi=150, bbox_inches="tight",
                facecolor="#F8FAFD")
    plt.close()

    # ── Texte du post LinkedIn ────────────────────────────
    debutants = stats_g[stats_g["PJ"] == 0]["equipe"].tolist()
    debutants_texte = (f"🆕 Débutants : {', '.join([drapeaux.get(d,'') + ' ' + d for d in debutants])}\n"
                       if debutants else "")

    # Construire les lignes d'équipes
    lignes_equipes = ""
    for i, (_, row) in enumerate(stats_g.iterrows()):
        drapeau = drapeaux.get(row["equipe"], "")
        etoile  = " ⭐ Favori historique" if i == 0 else ""
        trophee = f" 🏆×{int(row['titres'])}" if row["titres"] > 0 else ""
        lignes_equipes += (f"{drapeau} {row['equipe']}{trophee}{etoile}\n"
                          f"   📊 {int(row['PJ'])} matchs | {int(row['V'])}V "
                          f"{int(row['N'])}N {int(row['D'])}D | "
                          f"{row['taux_V']:.1f}% victoires | {int(row['DB']):+d} buts\n\n")

    post = f"""⚽ #FIFAWorldCup2026 — Groupe {groupe} 🔍

Qui a le meilleur palmarès historique dans ce groupe ?
Voici ce que disent les données 📊

{lignes_equipes}{debutants_texte}
📌 Analyse basée sur {int(stats_g['PJ'].sum())} matchs de Coupe du Monde (1930–2022)

💡 Le favori historique n'est pas toujours le favori du terrain —
mais les chiffres ne mentent pas.

#Football #DataAnalysis #WorldCup2026 #Groupe{groupe} #DataScience #FIFA
"""

    posts_linkedin.append({
        "groupe":    groupe,
        "favori":    favori,
        "post":      post,
        "graphique": chemin_graphique,
    })

    print(f"✅ Groupe {groupe} — {chemin_graphique}")

# ── Sauvegarder tous les posts dans un fichier texte ─────
with open("outputs/linkedin/posts_linkedin.txt", "w", encoding="utf-8") as f:
    for p in posts_linkedin:
        f.write(f"{'='*60}\n")
        f.write(f"GROUPE {p['groupe']} — Favori : {p['favori']}\n")
        f.write(f"Graphique : {p['graphique']}\n")
        f.write(f"{'='*60}\n")
        f.write(p["post"])
        f.write("\n\n")

print("\n✅ Tous les visuels et posts sont prêts !")
print("   🖼️  outputs/linkedin/groupe_A.png → groupe_L.png")
print("   📄  outputs/linkedin/posts_linkedin.txt")









# ══════════════════════════════════════════════════════════
# EXPORTACIÓN — Dashboard HTML interactivo
# Genera wc2026_dashboard.html en la carpeta outputs/
# ══════════════════════════════════════════════════════════

import json
import os

os.makedirs("outputs", exist_ok=True)

# ── Preparar datos desde tus DataFrames ya calculados ────
stats_export = []
for _, row in stats_wc.iterrows():
    stats_export.append({
        "equipe":      row["equipe"],
        "PJ":          int(row["PJ"]),
        "V":           int(row["V"]),
        "N":           int(row["N"]),
        "D":           int(row["D"]),
        "BF":          int(row["BF"]),
        "BC":          int(row["BC"]),
        "DB":          int(row["DB"]),
        "PTS":         int(row["PTS"]),
        "taux_V":      float(row["taux_V"]),
        "titres":      int(row["titres"]),
        "finales":     int(row["finales"]),
        "annees":      str(row["annees_titres"]),
        "groupe":      str(row["groupe"]),
    })

groupes_export = groupes_2026  # ya lo tienes definido en tu notebook

# Convertir a JSON para inyectar en el HTML
stats_json   = json.dumps(stats_export,   ensure_ascii=False)
groupes_json = json.dumps(groupes_export, ensure_ascii=False)

# ── Template HTML ─────────────────────────────────────────
html = f"""<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>⚽ Analyse FIFA World Cup 2026</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.min.js"></script>
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@300;400;500;700&display=swap" rel="stylesheet">
<style>
  :root {{
    --bg:#060d18;--surface:#0d1b2e;--surface2:#132238;
    --gold:#f0c040;--blue:#185fa5;--blue-light:#4a9eff;
    --green:#22c55e;--red:#ef4444;--text:#e8eef6;--muted:#7a90a8;
    --border:rgba(255,255,255,0.07);--radius:12px;
  }}
  *{{box-sizing:border-box;margin:0;padding:0;}}
  body{{background:var(--bg);color:var(--text);font-family:'DM Sans',sans-serif;overflow-x:hidden;}}
  header{{position:relative;padding:60px 40px 50px;text-align:center;overflow:hidden;}}
  header::before{{content:'';position:absolute;inset:0;
    background:radial-gradient(ellipse 80% 60% at 50% -10%,rgba(240,192,64,.18) 0%,transparent 70%),
               radial-gradient(ellipse 50% 40% at 20% 100%,rgba(24,95,165,.25) 0%,transparent 60%),
               radial-gradient(ellipse 50% 40% at 80% 100%,rgba(24,95,165,.2) 0%,transparent 60%);
    pointer-events:none;}}
  .header-badge{{display:inline-block;background:var(--gold);color:#060d18;font-family:'Bebas Neue',sans-serif;
    font-size:13px;letter-spacing:3px;padding:4px 16px;border-radius:4px;margin-bottom:18px;}}
  header h1{{font-family:'Bebas Neue',sans-serif;font-size:clamp(48px,8vw,96px);letter-spacing:4px;line-height:.9;
    background:linear-gradient(135deg,#fff 30%,var(--gold) 70%);-webkit-background-clip:text;
    -webkit-text-fill-color:transparent;background-clip:text;margin-bottom:14px;}}
  header p{{color:var(--muted);font-size:15px;font-weight:300;letter-spacing:1px;}}
  .header-stats{{display:flex;justify-content:center;gap:40px;margin-top:36px;flex-wrap:wrap;}}
  .hstat{{text-align:center;}}
  .hstat-val{{font-family:'Bebas Neue',sans-serif;font-size:38px;color:var(--gold);letter-spacing:2px;}}
  .hstat-label{{font-size:11px;color:var(--muted);letter-spacing:2px;text-transform:uppercase;margin-top:2px;}}
  .tabs{{display:flex;justify-content:center;gap:4px;padding:0 40px 30px;flex-wrap:wrap;}}
  .tab-btn{{background:var(--surface);border:1px solid var(--border);color:var(--muted);padding:10px 22px;
    border-radius:8px;font-family:'DM Sans',sans-serif;font-size:13px;font-weight:500;letter-spacing:.5px;cursor:pointer;transition:all .2s;}}
  .tab-btn:hover{{color:var(--text);border-color:rgba(255,255,255,.15);}}
  .tab-btn.active{{background:var(--gold);color:#060d18;border-color:var(--gold);font-weight:700;}}
  .content{{padding:0 40px 60px;max-width:1400px;margin:0 auto;}}
  .section{{display:none;}}.section.active{{display:block;}}
  .section-title{{font-family:'Bebas Neue',sans-serif;font-size:32px;letter-spacing:3px;color:var(--gold);margin-bottom:6px;}}
  .section-sub{{color:var(--muted);font-size:13px;margin-bottom:30px;letter-spacing:.5px;}}
  .grid-2{{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:24px;}}
  .grid-3{{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-bottom:24px;}}
  @media(max-width:900px){{.grid-2,.grid-3{{grid-template-columns:1fr;}}}}
  .card{{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:24px;}}
  .card-title{{font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:var(--muted);margin-bottom:16px;}}
  .chart-wrap{{position:relative;height:340px;}}
  .chart-wrap-lg{{position:relative;height:460px;}}
  .chart-wrap-sm{{position:relative;height:240px;}}
  .rank-table{{width:100%;border-collapse:collapse;font-size:13px;}}
  .rank-table th{{text-align:left;color:var(--muted);font-weight:600;font-size:11px;letter-spacing:1.5px;
    text-transform:uppercase;padding:8px 10px;border-bottom:1px solid var(--border);}}
  .rank-table th.r,.rank-table td.r{{text-align:right;}}
  .rank-table td{{padding:10px;border-bottom:1px solid rgba(255,255,255,.04);}}
  .rank-table tr:hover td{{background:rgba(255,255,255,.03);}}
  .rank-num{{color:var(--muted);font-size:12px;font-weight:700;width:28px;display:inline-block;}}
  .badge-group{{display:inline-block;background:var(--blue);color:#fff;font-size:10px;font-weight:700;
    padding:1px 7px;border-radius:4px;margin-left:6px;vertical-align:middle;letter-spacing:.5px;}}
  .bar-mini{{display:inline-block;height:6px;border-radius:3px;
    background:linear-gradient(90deg,var(--blue),var(--blue-light));vertical-align:middle;margin-right:8px;}}
  .groupes-grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:24px;}}
  @media(max-width:1100px){{.groupes-grid{{grid-template-columns:repeat(2,1fr);}}}}
  @media(max-width:600px){{.groupes-grid{{grid-template-columns:1fr;}}}}
  .groupe-card{{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);overflow:hidden;}}
  .groupe-header{{background:var(--blue);padding:10px 16px;display:flex;align-items:center;gap:10px;}}
  .groupe-letter{{font-family:'Bebas Neue',sans-serif;font-size:28px;color:var(--gold);letter-spacing:2px;line-height:1;}}
  .groupe-label{{font-size:11px;color:rgba(255,255,255,.7);text-transform:uppercase;letter-spacing:1px;}}
  .groupe-body{{padding:10px 0;}}
  .groupe-team{{display:flex;align-items:center;justify-content:space-between;padding:7px 16px;font-size:13px;transition:background .15s;}}
  .groupe-team:hover{{background:rgba(255,255,255,.04);}}
  .groupe-team.favori{{background:rgba(240,192,64,.07);border-left:3px solid var(--gold);}}
  .groupe-team .pts{{font-size:12px;color:var(--muted);}}
  .groupe-team .pts span{{color:var(--gold);font-weight:700;}}
  .debutant-tag{{font-size:9px;background:rgba(239,68,68,.2);color:#ef4444;border-radius:3px;
    padding:1px 5px;margin-left:4px;letter-spacing:.5px;font-weight:700;text-transform:uppercase;}}
  .champion-card{{background:linear-gradient(135deg,var(--surface2) 0%,var(--surface) 100%);
    border:1px solid rgba(240,192,64,.2);border-radius:var(--radius);padding:20px;
    display:flex;align-items:center;gap:16px;}}
  .champion-trophies{{font-size:28px;line-height:1;min-width:60px;text-align:center;}}
  .champion-name{{font-family:'Bebas Neue',sans-serif;font-size:22px;letter-spacing:2px;}}
  .champion-meta{{font-size:12px;color:var(--muted);margin-top:4px;}}
  .champion-group{{font-size:11px;color:var(--gold);font-weight:700;margin-top:4px;letter-spacing:1px;}}
  .cache-badge{{display:inline-flex;align-items:center;gap:6px;background:rgba(34,197,94,.12);
    border:1px solid rgba(34,197,94,.3);border-radius:20px;padding:4px 12px;
    font-size:11px;color:var(--green);letter-spacing:.5px;margin-bottom:20px;}}
  .cache-dot{{width:6px;height:6px;border-radius:50%;background:var(--green);animation:pulse 2s infinite;}}
  @keyframes pulse{{0%,100%{{opacity:1;}}50%{{opacity:.4;}}}}
  .info-box{{background:var(--surface2);border:1px solid var(--border);border-radius:8px;
    padding:12px 16px;font-size:12px;color:var(--muted);margin-top:12px;line-height:1.6;}}
  footer{{text-align:center;padding:24px;color:var(--muted);font-size:12px;
    border-top:1px solid var(--border);letter-spacing:.5px;}}
</style>
</head>
<body>
<header>
  <div class="header-badge">PROJET DATA SCIENCE</div>
  <h1>FIFA WORLD<br>CUP 2026</h1>
  <p>Analyse historique des équipes qualifiées • Dataset Kaggle 1872–2025</p>
  <div class="header-stats" id="headerStats"></div>
</header>
<div class="tabs" id="tabsNav"></div>
<div class="content">
  <div class="section active" id="sec-classement">
    <div class="section-title">CLASSEMENT HISTORIQUE</div>
    <div class="section-sub">Points cumulés en FIFA World Cup de toutes les équipes qualifiées pour 2026</div>
    <div class="cache-badge"><span class="cache-dot"></span> Données en cache localStorage</div>
    <div class="grid-2">
      <div class="card"><div class="card-title">Top 10 — Points historiques</div><div class="chart-wrap"><canvas id="chartPoints"></canvas></div></div>
      <div class="card"><div class="card-title">Top 10 — Taux de victoire (%)</div><div class="chart-wrap"><canvas id="chartTaux"></canvas></div></div>
    </div>
    <div class="card"><div class="card-title">Classement complet</div><table class="rank-table" id="rankTable"></table></div>
  </div>
  <div class="section" id="sec-groupes">
    <div class="section-title">GROUPES 2026</div>
    <div class="section-sub">Tirage au sort FIFA — 5 décembre 2025 • 12 groupes • 48 équipes</div>
    <div class="grid-2" style="margin-bottom:20px">
      <div class="card"><div class="card-title">Moyenne pts historiques par grupo</div><div class="chart-wrap"><canvas id="chartGroupPts"></canvas></div></div>
      <div class="card"><div class="card-title">Favori vs promedio del grupo</div><div class="chart-wrap"><canvas id="chartGroupFavori"></canvas></div></div>
    </div>
    <div class="groupes-grid" id="groupesGrid"></div>
  </div>
  <div class="section" id="sec-scatter">
    <div class="section-title">PERFORMANCE GLOBALE</div>
    <div class="section-sub">Taux de victoire vs. points historiques — toutes les équipes qualifiées</div>
    <div class="card"><div class="card-title">Scatter — Taux victoire × Points</div><div class="chart-wrap-lg"><canvas id="chartScatter"></canvas></div>
      <div class="info-box">⚡ X : Taux de victoire (%). Y : Points historiques (V×3 + N×1). Les lignes marquent 50% et 50 pts.</div>
    </div>
    <div class="grid-3" style="margin-top:20px">
      <div class="card"><div class="card-title">Distribution — Parties jouées</div><div class="chart-wrap-sm"><canvas id="chartPJ"></canvas></div></div>
      <div class="card"><div class="card-title">Distribution — Buts pour</div><div class="chart-wrap-sm"><canvas id="chartBF"></canvas></div></div>
      <div class="card"><div class="card-title">Buts pour vs contre (Top 12)</div><div class="chart-wrap-sm"><canvas id="chartButs"></canvas></div></div>
    </div>
  </div>
  <div class="section" id="sec-palmares">
    <div class="section-title">PALMARÈS</div>
    <div class="section-sub">Champions du monde qualifiés pour 2026</div>
    <div class="card" style="margin-bottom:20px"><div class="card-title">Titres FIFA World Cup</div><div class="chart-wrap"><canvas id="chartPalmares"></canvas></div></div>
    <div id="palmaresCards" style="display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:14px;"></div>
  </div>
</div>
<footer>⚽ Analyse du Football International 1872–2025 · Dataset Kaggle (martj42) · Projet Data Science</footer>

<script>
// ── Datos inyectados desde Python ────────────────────────
const RAW_STATS  = {stats_json};
const GROUPES    = {groupes_json};
const CACHE_KEY  = "wc2026_stats_v1";

// ── Cache localStorage ────────────────────────────────────
function initCache() {{
  try {{
    const cached = localStorage.getItem(CACHE_KEY);
    if (cached) {{
      const p = JSON.parse(cached);
      if (Date.now() - p.ts < 86400000) {{
        console.log("✅ Cache localStorage actif");
        return p.data;
      }}
    }}
  }} catch(e) {{}}
  const data = {{ stats: [...RAW_STATS].sort((a,b) => b.PTS - a.PTS) }};
  try {{ localStorage.setItem(CACHE_KEY, JSON.stringify({{ ts: Date.now(), data }})); }} catch(e) {{}}
  console.log("✅ Données mises en cache");
  return data;
}}

// ── Tabs ──────────────────────────────────────────────────
const TABS = [
  {{id:"classement",label:"🏆 Classement"}},
  {{id:"groupes",   label:"🗂️ Groupes 2026"}},
  {{id:"scatter",   label:"📊 Performance"}},
  {{id:"palmares",  label:"🥇 Palmarès"}},
];
function initTabs() {{
  const nav = document.getElementById("tabsNav");
  TABS.forEach(t => {{
    const btn = document.createElement("button");
    btn.className = "tab-btn" + (t.id==="classement"?" active":"");
    btn.textContent = t.label;
    btn.onclick = () => {{
      document.querySelectorAll(".section").forEach(s=>s.classList.remove("active"));
      document.querySelectorAll(".tab-btn").forEach(b=>b.classList.remove("active"));
      document.getElementById("sec-"+t.id).classList.add("active");
      btn.classList.add("active");
    }};
    nav.appendChild(btn);
  }});
}}

// ── Chart.js defaults ─────────────────────────────────────
Chart.defaults.color = "#7a90a8";
Chart.defaults.font.family = "'DM Sans', sans-serif";
Chart.defaults.font.size = 12;

// ── Header stats ──────────────────────────────────────────
function renderHeaderStats(stats) {{
  const el = document.getElementById("headerStats");
  const items = [
    {{val:"48",                               label:"Équipes qualifiées"}},
    {{val:"12",                               label:"Groupes"}},
    {{val:stats.reduce((a,b)=>a+b.BF,0).toLocaleString(), label:"Buts historiques"}},
    {{val:stats.filter(s=>s.titres>0).length, label:"Ex-champions"}},
    {{val:stats.filter(s=>s.PJ===0).length,   label:"Débutants en CM"}},
  ];
  items.forEach(i => {{
    el.innerHTML += `<div class="hstat"><div class="hstat-val">${{i.val}}</div><div class="hstat-label">${{i.label}}</div></div>`;
  }});
}}

// ── Classement ────────────────────────────────────────────
function renderClassement(stats) {{
  const top10 = stats.slice(0,10);
  const ctx1 = document.getElementById("chartPoints").getContext("2d");
  const g1 = ctx1.createLinearGradient(0,0,500,0);
  g1.addColorStop(0,"#f0c040"); g1.addColorStop(1,"#185fa5");
  new Chart(ctx1,{{type:"bar",data:{{labels:[...top10.map(s=>s.equipe)].reverse(),
    datasets:[{{data:[...top10.map(s=>s.PTS)].reverse(),backgroundColor:g1,borderRadius:6,borderSkipped:false}}]}},
    options:{{indexAxis:"y",responsive:true,maintainAspectRatio:false,
      plugins:{{legend:{{display:false}},tooltip:{{callbacks:{{label:c=>" "+c.raw+" pts"}}}}}},
      scales:{{x:{{grid:{{color:"rgba(255,255,255,.04)"}}}},y:{{grid:{{display:false}},ticks:{{color:"#e8eef6",font:{{weight:"600"}}}}}}}}
    }}}});

  const ctx2 = document.getElementById("chartTaux").getContext("2d");
  const colors = [...top10.map(s=>s.taux_V)].reverse().map((_,i)=>i===9?"#f0c040":i>=7?"#185fa5":"#4a9eff");
  new Chart(ctx2,{{type:"bar",data:{{labels:[...top10.map(s=>s.equipe)].reverse(),
    datasets:[{{data:[...top10.map(s=>s.taux_V)].reverse(),backgroundColor:colors,borderRadius:6,borderSkipped:false}}]}},
    options:{{indexAxis:"y",responsive:true,maintainAspectRatio:false,
      plugins:{{legend:{{display:false}},tooltip:{{callbacks:{{label:c=>" "+c.raw+"%"}}}}}},
      scales:{{x:{{grid:{{color:"rgba(255,255,255,.04)"}},ticks:{{callback:v=>v+"%"}},max:80}},y:{{grid:{{display:false}},ticks:{{color:"#e8eef6",font:{{weight:"600"}}}}}}}}
    }}}});

  const table = document.getElementById("rankTable");
  const maxPts = stats[0].PTS;
  table.innerHTML = `<thead><tr><th>#</th><th>Équipe</th><th class="r">PJ</th><th class="r">V</th>
    <th class="r">N</th><th class="r">D</th><th class="r">BF</th><th class="r">BC</th>
    <th class="r">DB</th><th class="r">PTS</th><th class="r">%V</th><th class="r">🏆</th></tr></thead><tbody>`;
  stats.forEach((s,i) => {{
    const bw = Math.round(s.PTS/maxPts*80);
    const dbColor = s.DB>0?"#22c55e":s.DB<0?"#ef4444":"#7a90a8";
    const dbVal   = s.DB>0?"+"+s.DB:s.DB;
    table.innerHTML += `<tr>
      <td><span class="rank-num">${{i+1}}</span></td>
      <td><span class="bar-mini" style="width:${{bw}}px"></span>
          <span style="font-weight:600">${{s.equipe}}</span>
          <span class="badge-group">${{s.groupe}}</span></td>
      <td class="r">${{s.PJ}}</td><td class="r">${{s.V}}</td><td class="r">${{s.N}}</td><td class="r">${{s.D}}</td>
      <td class="r">${{s.BF}}</td><td class="r">${{s.BC}}</td>
      <td class="r" style="color:${{dbColor}}">${{dbVal}}</td>
      <td class="r" style="font-weight:700;color:${{s.PTS>0?"#f0c040":"#7a90a8"}}">${{s.PTS}}</td>
      <td class="r">${{s.taux_V}}%</td>
      <td class="r">${{s.titres>0?"🏆".repeat(s.titres):"—"}}</td></tr>`;
  }});
  table.innerHTML += "</tbody>";
}}

// ── Groupes ───────────────────────────────────────────────
function renderGroupes(stats) {{
  const statMap = {{}};
  stats.forEach(s => statMap[s.equipe] = s);
  const gLabels = Object.keys(GROUPES).sort();
  const gMoy = gLabels.map(g => Math.round(GROUPES[g].map(e=>statMap[e]?.PTS||0).reduce((a,b)=>a+b,0)/GROUPES[g].length));
  const gFav = gLabels.map(g => Math.max(...GROUPES[g].map(e=>statMap[e]?.PTS||0)));

  const g3 = ctx3 => {{
    const ctx = document.getElementById("chartGroupPts").getContext("2d");
    const gr  = ctx.createLinearGradient(0,0,0,300);
    gr.addColorStop(0,"#f0c040"); gr.addColorStop(1,"#185fa5");
    new Chart(ctx,{{type:"bar",data:{{labels:gLabels.map(g=>"Gr. "+g),datasets:[{{label:"Pts moy.",data:gMoy,backgroundColor:gr,borderRadius:6}}]}},
      options:{{responsive:true,maintainAspectRatio:false,plugins:{{legend:{{display:false}}}},
        scales:{{x:{{grid:{{display:false}},ticks:{{color:"#e8eef6"}}}},y:{{grid:{{color:"rgba(255,255,255,.04)"}}}}}}
      }}}});
  }}; g3();

  new Chart(document.getElementById("chartGroupFavori").getContext("2d"),{{type:"bar",
    data:{{labels:gLabels.map(g=>"Gr. "+g),datasets:[
      {{label:"Favori (pts)",data:gFav,backgroundColor:"rgba(240,192,64,.85)",borderRadius:6}},
      {{label:"Moyenne (pts)",data:gMoy,backgroundColor:"rgba(74,158,255,.6)",borderRadius:6}},
    ]}},
    options:{{responsive:true,maintainAspectRatio:false,
      plugins:{{legend:{{labels:{{color:"#e8eef6"}}}}}},
      scales:{{x:{{grid:{{display:false}},ticks:{{color:"#e8eef6"}}}},y:{{grid:{{color:"rgba(255,255,255,.04)"}}}}}}
    }}}});

  const grid = document.getElementById("groupesGrid");
  gLabels.forEach(g => {{
    const eqs = GROUPES[g].map(e => statMap[e]||{{equipe:e,PTS:0,PJ:0}}).sort((a,b)=>b.PTS-a.PTS);
    const maxP = eqs[0]?.PTS||0;
    let html = eqs.map((s,i) => {{
      const isNew = s.PJ===0;
      const isFav = i===0 && maxP>0;
      return `<div class="groupe-team ${{isFav?"favori":""}}">
        <span>${{s.equipe}}${{isNew?'<span class="debutant-tag">NEW</span>':""}}</span>
        <span class="pts">${{s.PTS>0?`<span>${{s.PTS}}</span> pts`:'<span style="color:#7a90a8">0</span> pts'}}</span>
      </div>`;
    }}).join("");
    grid.innerHTML += `<div class="groupe-card">
      <div class="groupe-header"><div>
        <div class="groupe-letter">G ${{g}}</div>
        <div class="groupe-label">Groupe ${{g}}</div>
      </div></div>
      <div class="groupe-body">${{html}}</div>
    </div>`;
  }});
}}

// ── Scatter + Distribuciones ──────────────────────────────
function renderScatter(stats) {{
  const gColors = {{"A":"#ef4444","B":"#f97316","C":"#eab308","D":"#22c55e",
    "E":"#14b8a6","F":"#3b82f6","G":"#8b5cf6","H":"#ec4899",
    "I":"#f0c040","J":"#4ade80","K":"#38bdf8","L":"#fb923c"}};
  const byG = {{}};
  stats.forEach(s => {{ if(!byG[s.groupe]) byG[s.groupe]=[]; byG[s.groupe].push(s); }});
  const datasets = Object.entries(byG).map(([g,pts]) => ({{
    label:"Groupe "+g, backgroundColor:gColors[g]||"#888", pointRadius:7, pointHoverRadius:10,
    data:pts.map(s=>({{x:s.taux_V,y:s.PTS,label:s.equipe}}))
  }}));
  new Chart(document.getElementById("chartScatter").getContext("2d"),{{
    type:"scatter", data:{{datasets}},
    options:{{responsive:true,maintainAspectRatio:false,
      plugins:{{legend:{{labels:{{color:"#7a90a8",boxWidth:10}},position:"right"}},
        tooltip:{{callbacks:{{label:c=>`${{c.raw.label}} — ${{c.raw.x}}% / ${{c.raw.y}} pts`}}}}}},
      scales:{{
        x:{{title:{{display:true,text:"Taux de victoire (%)",color:"#7a90a8"}},grid:{{color:"rgba(255,255,255,.04)"}},ticks:{{color:"#7a90a8",callback:v=>v+"%"}}}},
        y:{{title:{{display:true,text:"Points historiques",color:"#7a90a8"}},grid:{{color:"rgba(255,255,255,.04)"}},ticks:{{color:"#7a90a8"}}}}
      }}
    }}
  }});

  const sPJ = [...stats].sort((a,b)=>b.PJ-a.PJ).slice(0,15);
  new Chart(document.getElementById("chartPJ").getContext("2d"),{{type:"bar",
    data:{{labels:sPJ.map(s=>s.equipe.split(" ")[0]),datasets:[{{data:sPJ.map(s=>s.PJ),backgroundColor:"#185fa5",borderRadius:4}}]}},
    options:{{responsive:true,maintainAspectRatio:false,plugins:{{legend:{{display:false}}}},
      scales:{{x:{{grid:{{display:false}},ticks:{{color:"#7a90a8",font:{{size:9}}}}}},y:{{grid:{{color:"rgba(255,255,255,.04)"}}}}}}
    }}}});

  const sBF = [...stats].sort((a,b)=>b.BF-a.BF).slice(0,15);
  new Chart(document.getElementById("chartBF").getContext("2d"),{{type:"bar",
    data:{{labels:sBF.map(s=>s.equipe.split(" ")[0]),datasets:[{{data:sBF.map(s=>s.BF),backgroundColor:"#22c55e",borderRadius:4}}]}},
    options:{{responsive:true,maintainAspectRatio:false,plugins:{{legend:{{display:false}}}},
      scales:{{x:{{grid:{{display:false}},ticks:{{color:"#7a90a8",font:{{size:9}}}}}},y:{{grid:{{color:"rgba(255,255,255,.04)"}}}}}}
    }}}});

  const t12 = [...stats].filter(s=>s.PJ>0).sort((a,b)=>b.PTS-a.PTS).slice(0,12);
  new Chart(document.getElementById("chartButs").getContext("2d"),{{type:"bar",
    data:{{labels:t12.map(s=>s.equipe.split(" ")[0]),datasets:[
      {{label:"Buts pour",data:t12.map(s=>s.BF),backgroundColor:"rgba(240,192,64,.8)",borderRadius:3}},
      {{label:"Buts contre",data:t12.map(s=>s.BC),backgroundColor:"rgba(239,68,68,.6)",borderRadius:3}},
    ]}},
    options:{{responsive:true,maintainAspectRatio:false,
      plugins:{{legend:{{labels:{{color:"#7a90a8",boxWidth:10,font:{{size:10}}}}}}}},
      scales:{{x:{{grid:{{display:false}},ticks:{{color:"#7a90a8",font:{{size:9}}}}}},y:{{grid:{{color:"rgba(255,255,255,.04)"}}}}}}
    }}}});
}}

// ── Palmarès ──────────────────────────────────────────────
function renderPalmares(stats) {{
  const champs = stats.filter(s=>s.titres>0).sort((a,b)=>b.titres-a.titres);
  const ctx = document.getElementById("chartPalmares").getContext("2d");
  const gP = ctx.createLinearGradient(0,0,0,300);
  gP.addColorStop(0,"#f0c040"); gP.addColorStop(1,"#e8a820");
  new Chart(ctx,{{type:"bar",data:{{labels:champs.map(s=>s.equipe),datasets:[
    {{label:"Titres",data:champs.map(s=>s.titres),backgroundColor:gP,borderRadius:6}},
    {{label:"Finales",data:champs.map(s=>s.finales),backgroundColor:"rgba(74,158,255,.5)",borderRadius:6}},
  ]}},options:{{responsive:true,maintainAspectRatio:false,
    plugins:{{legend:{{labels:{{color:"#e8eef6"}}}}}},
    scales:{{x:{{grid:{{display:false}},ticks:{{color:"#e8eef6",font:{{weight:"600"}}}}}},y:{{grid:{{color:"rgba(255,255,255,.04)"}},ticks:{{stepSize:1}}}}}}
  }}}});

  const container = document.getElementById("palmaresCards");
  stats.filter(s=>s.titres>0||s.finales>0).sort((a,b)=>b.titres-a.titres||b.finales-a.finales)
    .forEach(s => {{
      container.innerHTML += `<div class="champion-card">
        <div class="champion-trophies">${{s.titres>0?"🏆".repeat(s.titres):"🥈"}}</div>
        <div>
          <div class="champion-name">${{s.equipe}}</div>
          <div class="champion-meta"><strong>${{s.titres}}</strong> titre${{s.titres>1?"s":""}} ·
            <strong>${{s.finales}}</strong> finale${{s.finales>1?"s":""}}
            ${{s.annees!=="—"?` · <span style="color:#f0c040">${{s.annees}}</span>`:""}}</div>
          <div class="champion-group">Groupe ${{s.groupe}} · ${{s.PTS}} pts · ${{s.taux_V}}% victoires</div>
        </div>
      </div>`;
    }});
}}

// ── Init ──────────────────────────────────────────────────
(function() {{
  initTabs();
  const {{ stats }} = initCache();
  renderHeaderStats(stats);
  renderClassement(stats);
  renderGroupes(stats);
  renderScatter(stats);
  renderPalmares(stats);
}})();
</script>
</body>
</html>"""

# ── Guardar el archivo ────────────────────────────────────
output_path = "outputs/wc2026_dashboard.html"
with open(output_path, "w", encoding="utf-8") as f:
    f.write(html)

print(f"✅ Dashboard HTML generado: {output_path}")

# En Google Colab — mostrar link de descarga
from IPython.display import FileLink, display
display(FileLink(output_path))