# -*- coding: utf-8 -*-
"""football.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fn8mvJ0euM1zoy4L6dStMRqJVe4DeBBu

# ⚽ **Analyse du Football International (1872–2025)**
### Projet — Exploration & Statistiques
"""



import pandas as pd
import kagglehub
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as mtick
import os

# ── CREAR CARPETAS NECESARIAS ────────────
# Crear las carpetas si no existen
os.makedirs("data_clean", exist_ok=True)
os.makedirs("outputs/graphs", exist_ok=True)
print("✅ Carpetas creadas: data_clean/, outputs/graphs/")

"""# Charger les Données

Téléchargement
"""

path = kagglehub.dataset_download("martj42/international-football-results-from-1872-to-2017")
print("Path:", path)

"""Chargement"""

results      = pd.read_csv(f"{path}/results.csv")
shootouts    = pd.read_csv(f"{path}/shootouts.csv")
goalscorers  = pd.read_csv(f"{path}/goalscorers.csv")
former_names = pd.read_csv(f"{path}/former_names.csv")

dfs = {
    "results":      results,
    "shootouts":    shootouts,
    "goalscorers":  goalscorers,
    "former_names": former_names,
}

print(dfs)

"""Inspection initiale"""

for name, df in dfs.items():
    print(f"\n{'='*55}")
    print(f"  {name.upper()}")
    print(f"{'='*55}")
    print(f"  Lignes × Colonnes : {df.shape}")
    print(f"  Colonnes          : {list(df.columns)}")
    print(f"\n  Types de données :")
    print(df.dtypes.to_string())
    print(f"\n  Valeurs nulles par colonne :")
    print(df.isnull().sum().to_string())
    print(f"\n  Doublons exacts : {df.duplicated().sum()}")
    print(f"\n  3 premières lignes :")
    print(df.head(3).to_string())
